export default{
    admin:{
        login:"api/v1/admin-login"
    },
    auth:{
        dispatch:"api/v1/auth/dispatch/login",
        medic:"api/v1/auth/medic/login"
    },
    medic:{
        admin:{
            details:"api/v1/medic/create-admin-details",
            login:"api/v1/medic/create-admin-login"
        },
        normal:{
            details:"api/v1/medic/create-details",
            login:"api/v1/medic/create-login"
        }
    },
    dispatch:{
        admin:{
            details:"api/v1/dispatcher/create-admin-details",
            login:"api/v1/dispatcher/create-admin-login"
        },
        normal:{
            details:"api/v1/dispatcher/create-details",
            login:"api/v1/dispatcher/create-login"
        }
    },
    hospital:{
        createAccount:"api/v1/hospital/create-account",
        createAccountAdmin:"api/v1/hospital/create-account-admin",
        updateHospitalInfo:"api/v1/hospital/update-hospital-info",
        getHospitalInfo:"api/v1/hospital/get-hospital-info",
        addImages:"api/v1/hospital/add-images"
    },
    ambulance:{}
}